CREATE PROC FI_SP_VerificaCliente

	@CPF		   VARCHAR (14)	

AS
BEGIN
	
	SELECT NOME, SOBRENOME, CPF, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID FROM CLIENTES WITH(NOLOCK) WHERE EXISTS (SELECT * FROM CLIENTES WHERE CPF = @CPF)

END